version: '3.9'

services:
  tech-news-server:
    build:
      context: ./tech-news-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./tech-news-server:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=TechNewsDB
      - POSTGRES_USER=aregene
      - POSTGRES_PASSWORD=Qq123456
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
